[package]
name = "rln"
type = "bin"
authors = [""]

[dependencies]
ec = { git = "https://github.com/noir-lang/noir-edwards", tag = "v0.1.1"}
binary_merkle_root = { git = "https://github.com/vplasencia/noir-circuits", tag = "binary-merkle-root-v0.0.1", directory = "circuits/binary-merkle-root" }