[package]
name = "semaphore"
type = "bin"
authors = [""]

[dependencies]
ec = { git = "https://github.com/noir-lang/noir-edwards", tag = "v0.1.1"}
binary_merkle_root = { path = "../binary-merkle-root" }